### ISSUE TITLE
Circuit diagram

### ISSUE THREAD

**Issue by grawlinson** [MadDoct/ESP-CrowAlarmInterface#2]
Hi! I'm currently using a Saleae logic analyser hooked up to DAT/CLK to reverse engineer the communications.

I would like to switch to using a ESP with logic level converters (3.3V - 5V) for bi-directional communications, but I am wondering how you've wired yours up because I don't see a 5V supply on the alarm panel.

**Comment by MadDoct** [comment]
I used the 5v coming from the esp8266 power supply... ;)
Why would you need the logic analyser? My code already has debug options... just send the payload "debugon" to the control topic and you'll receive all the messages from and to the alarm in the debug_data topic, if you really need to... What features are you trying to add that aren't there already?

**Comment by grawlinson** [comment]
I don’t have any ESP8266’s, my alarm panel is in an awkward spot (no nearby power sources) so I am having to design a PCB that attaches to the AC power supply inside the panel (before the fuse) due to the power limits of the panel itself being unknown (the documentation for it is a bit vague).

I already had the logic analyzer on hand so I thought why not see what the communications is like.

**Comment by MadDoct** [comment]
You can power an esp32 from the panel with a step-down without issues... I have been doing just that for several years. I had an esp32 "sensing" the voltage levels of each zone, before doing this project

**Comment by grawlinson** [comment]
Good to know! That'll make the PCB design a lot simpler then. :)
