### ISSUE TITLE
How to flash in a wemos D1 mini (ESP8266)

### ISSUE THREAD

**Issue by japamar** [MadDoct/ESP-CrowAlarmInterface#3]
I tryed to flash my Wemos D1, but without success.
Can you explain how to do this? 
I used arduino and platformio (I tried this 2 tools with no success).

Peço desculpa mas não sei como compilar o ficheiro main.cpp para obter um ficheiro .bin que permita programar o ESP.
Qual o procedimento para programar e que ferramentas usar?
Peço esculpa mais uma vez e obrigado.

**Comment by MadDoct** [comment]
Don't use just main.cpp. You must download this project to a folder. Open it in platformio and compile and upload it after changing the ssid, password and such... Please provide additional info about what happened to you...

Na verdade deverá ser simples. Não uses o main.cpp separadamente. É mais fácil fazer download do zip deste projecto. Descompactar para uma pasta. Adiciona esse projecto ao platformio e compila e faz upload após mudares SSID, password e afins. O próprio platformio flasha o wemos directamente. Terás que fornecer mais informação sobre o que falhou para te poder ajudar...

**Comment by japamar** [comment]
Thank you for the tips. 
I followed your instructions and it worked perfectly. I managed to program the ESP module and can see in the Platformio terminal that it is connected to WIFI and MQTT. 
I just need to integrate it into Home Assistant. I have already added the code from the alarm-bus.yaml file to the configuration.yaml file, but I am not able to make the entities appear in HA.
Any additional tips?

**Comment by MadDoct** [comment]
Do you yave mqtt setup in your home-assistant? If so, you should now have an alarm entity. As for the motion sensors based on the PIRs you must use mqtt binary sensors. It shouldn't be too hard to do. If you need help with that, I'll add an example soon... Or you could ask for help in the CPHA discord (the Portuguese home assistant comunity discord...)

Also, a good way to know if it is communicating with mqtt correctly, is using "mqtt explorer". It's an amazing piece of software. Also important - if the wemos isn't connected to the alarm yet, it won't send information on the status, obviously! ;)

**Comment by MadDoct** [comment]
I have now created an example for the PIR sensors in the folder HAConfig
